name: sonar-stack


services:
  sonarQube:
    image: sonarqube:lts
    depends_on:
      - postgresql
    restart: always
    networks:
      - nt
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgresql:5432/dbname
      - SONAR_JDBC_USERNAME=user
      - SONAR_JDBC_PASSWORD=pass
  postgresql:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbname
    networks:
      - nt
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  nt:
    driver: bridge


volumes:
  postgres_data:
  sonar_data:
  sonar_logs:
  sonar_extensions:
